{{- if .Values.services.influxdb.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: influxdb-secret
type: Opaque
stringData:
  admin.username: admin
  admin.password: admin123456
  app.username: app
  app.password: app123456
  read.username: read
  read.password: read123456
{{- end }}
