apiVersion: eventing.knative.dev/v1alpha1
kind: KafkaSink
metadata:
  name: iot-commands
spec:
  bootstrapServers:
    - drogue-iot-kafka-bootstrap.drogue-iot.svc.cluster.local.:9092
  contentMode: binary
  topic: iot-commands
