[workspace]

members = [
    "endpoint-common",
    "http-endpoint",
    "mqtt-endpoint",
    "console-common",
    "console-backend",
    "console-frontend",
    "authentication-service",
    "device-management-service",
    "database-common",
    "service-common",
    "service-api",
    "command-endpoint",
    "test-common",
]

[patch.crates-io]
testcontainers = { git = "https://github.com/testcontainers/testcontainers-rs", rev = "fe51e06fb2c44b1d3e3fd627cedea3fd582487ef"}
#ntex-mqtt = { path = "../ntex-mqtt" }
#patternfly-yew = { path = "../patternfly-yew" }
#drogue-ttn = { path = "../drogue-ttn" }
#diesel = { git = 'https://github.com/diesel-rs/diesel', rev = "06494e8bdfe774bac9be5cab488b3d0cbec97f4e" }
#openid = { git = "https://github.com/ctron/openid.git", branch = "feature/custom_ca_1" }
actix-cors = { git = "https://github.com/ctron/actix-extras", rev = "8718685f0237ac8cf39c8f73a272bd1d7205ba8e" }
actix-web-httpauth = { git = "https://github.com/ctron/actix-extras", rev = "8718685f0237ac8cf39c8f73a272bd1d7205ba8e" }
#reqwest = { git = "https://github.com/ctron/reqwest", branch = "feature/basic_auth_wasm_1" }
#cloudevents-sdk = { git = "https://github.com/cloudevents/sdk-rust", rev = "da40d3d563e6a317122119597fc5742772262d6a" }
#cloudevents-sdk-reqwest = { git = "https://github.com/cloudevents/sdk-rust", rev = "da40d3d563e6a317122119597fc5742772262d6a" }
#cloudevents-sdk-rdkafka = { git = "https://github.com/cloudevents/sdk-rust", rev = "da40d3d563e6a317122119597fc5742772262d6a" }
