[workspace]

members = [
    "endpoint-common",
    "http-endpoint",
    "mqtt-endpoint",
    "console-common",
    "console-backend",
    "console-frontend",
    "authentication-service",
    "device-management-service",
    "database-common",
    "service-common",
    "service-api",
    "command-endpoint",
    "test-common",
    "registry-events",
    "outbox-controller",
    "user-auth-service",
    "integration-common",
    "mqtt-integration",
]

[patch.crates-io]
testcontainers = { git = "https://github.com/testcontainers/testcontainers-rs", rev = "fe51e06fb2c44b1d3e3fd627cedea3fd582487ef" }
#patternfly-yew = { path = "../patternfly-yew" }
#patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", branch = "main" }
#reqwest = { git = "https://github.com/ctron/reqwest", branch = "feature/basic_auth_wasm_1" }

# required for https://github.com/ntex-rs/ntex-mqtt/pull/48
ntex-mqtt = { git = "https://github.com/ctron/ntex-mqtt", rev = "23c1a1fb47059a4b3780eb43204f4491e1abb226" }

# required due to missing "beta" versions of more recent "beta" actix versions
actix-cors = { git = "https://github.com/ctron/actix-extras", rev = "a580096e7c7e929ac9b6b77abee7403890006e0a" }
actix-web-httpauth = { git = "https://github.com/ctron/actix-extras", rev = "a580096e7c7e929ac9b6b77abee7403890006e0a" }

# required du to missing "beta" versions for more recent "beta" actix versions
cloudevents-sdk = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
cloudevents-sdk-actix-web = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
cloudevents-sdk-reqwest = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
cloudevents-sdk-rdkafka = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
