[workspace]
resolver = "2"

members = [
    "endpoint-common",
    "http-endpoint",
    "mqtt-endpoint",
    "console-common",
    "console-backend",
    "console-frontend",
    "authentication-service",
    "device-management-service",
    "database-common",
    "service-common",
    "service-api",
    "command-endpoint",
    "test-common",
    "registry-events",
    "outbox-controller",
    "user-auth-service",
    "integration-common",
    "mqtt-integration",
    "ttn-operator",
    "api-key-service",
    "admin-service",
]

[patch.crates-io]
testcontainers = { git = "https://github.com/testcontainers/testcontainers-rs", rev = "fe51e06fb2c44b1d3e3fd627cedea3fd582487ef" }
#patternfly-yew = { path = "../patternfly-yew" }
patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", rev = "bb52b8f4d8e4cf656a644bbfee4b9aa679fb9f78" }
#reqwest = { git = "https://github.com/ctron/reqwest", branch = "feature/basic_auth_wasm_1" }
#drogue-ttn = { git = "https://github.com/drogue-iot/drogue-ttn", rev = "1898ac0a6af51dc3a99c9f291049e3fd993c69c6"}

#drogue-client = { git = "https://github.com/drogue-iot/drogue-client", rev = "b7779aeacbbeff1950701a88399e6b08c664e634" }
#drogue-client = { path = "../drogue-client" }

# required due to missing "beta" versions of more recent "beta" actix versions
actix-cors = { git = "https://github.com/ctron/actix-extras", rev = "a580096e7c7e929ac9b6b77abee7403890006e0a" }
actix-web-httpauth = { git = "https://github.com/ctron/actix-extras", rev = "a580096e7c7e929ac9b6b77abee7403890006e0a" }

# required du to missing "beta" versions for more recent "beta" actix versions
cloudevents-sdk = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
cloudevents-sdk-actix-web = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
cloudevents-sdk-reqwest = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
cloudevents-sdk-rdkafka = { git = "https://github.com/ctron/sdk-rust", rev = "66ffe07a16fb7bac780a24f31042eed564514301" }
