[workspace]

members = [
    "endpoint-common",
    "coap-endpoint",
    "http-endpoint",
    "mqtt-endpoint",
    "console-common",
    "console-backend",
    "console-frontend",
    "authentication-service",
    "device-management-service",
    "database-common",
    "service-common",
    "service-api",
    "command-endpoint",
    "test-common",
    "registry-events",
    "outbox-controller",
    "user-auth-service",
    "integration-common",
    "mqtt-common",
    "mqtt-integration",
    "operator-common",
    "ttn-operator",
    "topic-operator",
    "api-key-service",
    "admin-service",
    "event-common",
    "websocket-integration",
    "server",
]

[patch.crates-io]
testcontainers = { git = "https://github.com/testcontainers/testcontainers-rs", rev = "fe51e06fb2c44b1d3e3fd627cedea3fd582487ef" }

patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", rev = "21660fc7849cb9fc29fc85493ee6b0bb389707b6" } # FIXME: awaiting release
#patternfly-yew = { path = "../patternfly-yew" }

#reqwest = { git = "https://github.com/ctron/reqwest", branch = "feature/basic_auth_wasm_1" }
#drogue-ttn = { git = "https://github.com/drogue-iot/drogue-ttn", rev = "cf0338a344309815f0f05e0d7d76acb712445175" } # FIXME: awaiting release

#drogue-client = { git = "https://github.com/drogue-iot/drogue-client", rev = "b47421c91b1c297616d738d855017ec513f60d48" } # FIXME: awaiting release
#operator-framework = { git = "https://github.com/ctron/operator-framework", rev = "b2b0fc88beca2deb07bad6a963d0d5322c9ddff8" }
#drogue-client = { path = "../drogue-client" }

# required due to missing "beta" versions of more recent "beta" actix versions
#actix-cors = { git = "https://github.com/ctron/actix-extras", rev = "5f08b566a04842667672d5802be2604b6054e285" }
#actix-web-httpauth = { git = "https://github.com/ctron/actix-extras", rev = "5f08b566a04842667672d5802be2604b6054e285" }

# required du to missing "beta" versions for more recent "beta" actix versions
cloudevents-sdk = { git = "https://github.com/cloudevents/sdk-rust", branch = "actix-web-4.0.0-beta.8" } # FIXME: pre-release branch
pq-sys = { git = "https://github.com/sgrif/pq-sys", rev = "3e367d53019a2740054d5dc6946e07931f1fb70b" }
