# This needs to be aligned with the builder image in drogue-iot/drogue-cloud-build-containers
[toolchain]
channel = "1.61.0"
components = ["rust-src", "rustfmt"]
targets = ["x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
