# This needs to be aligned with the builder image in drogue-iot/drogue-cloud-build-containers
[toolchain]
channel = "1.56.1"
components = [ "rust-src", "rustfmt" ]
targets = ["x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
