apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - credential-sso.yaml
  - instance.yaml
  - realm.yaml
  - client.yaml
  - client-grafana.yaml
  - client-services.yaml
  - user.yaml
