kind: Deployment
apiVersion: apps/v1
metadata:
  name: mqtt-integration
  labels:
    app.kubernetes.io/name: mqtt-integration
    app.kubernetes.io/part-of: integrations
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt-integration
      app.kubernetes.io/part-of: integrations
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqtt-integration
        app.kubernetes.io/part-of: integrations
    spec:
      initContainers:
        - name: wait-for-client-secret
          image: registry.access.redhat.com/ubi8-minimal
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - |
              echo "Waiting for client secret to be populated (/etc/client-secret/CLIENT_SECRET)..."
              while test -z "$(cat /etc/client-secret/CLIENT_SECRET)"; do
                sleep 1
              done
          volumeMounts:
            - mountPath: /etc/client-secret
              name: client-secret
              readOnly: true
          env:
            - name: K_CE_OVERRIDES
              value: ""
      containers:
        - name: service
          image: ghcr.io/drogue-iot/mqtt-integration:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: debug
            - name: BIND_ADDR_MQTT
              value: "0.0.0.0:8883"
            - name: HEALTH__BIND_ADDR
              value: "0.0.0.0:9090"
            - name: CERT_BUNDLE_FILE
              value: /etc/endpoint/tls.crt
            - name: KEY_FILE
              value: /etc/endpoint/tls.key
            - name: INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: instance
            - name: OAUTH__DROGUE__CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-drogue
                  key: CLIENT_ID
            - name: OAUTH__DROGUE__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-drogue
                  key: CLIENT_SECRET
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE__KAFKA_TOPIC
              value: knative-messaging-kafka.$(NAMESPACE).iot-channel
            - name: USER_AUTH__CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_ID
            - name: USER_AUTH__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_SECRET
            - name: REGISTRY__CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_ID
            - name: REGISTRY__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_SECRET
            - name: K_CE_OVERRIDES
              value: ""
          ports:
            - containerPort: 8883
              name: service
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
          volumeMounts:
            - mountPath: /etc/endpoint
              name: endpoint-tls
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /readiness
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /liveness
      volumes:
        - name: endpoint-tls
          secret:
            secretName: mqtt-endpoint-tls
        - name: client-secret
          secret:
            secretName: keycloak-client-secret-drogue
