kind: Deployment
apiVersion: apps/v1
metadata:
  name: http-endpoint
  labels:
    app.kubernetes.io/name: http-endpoint
    app.kubernetes.io/part-of: endpoints
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-endpoint
      app.kubernetes.io/part-of: endpoints
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-endpoint
        app.kubernetes.io/part-of: endpoints
    spec:
      containers:
        - name: endpoint
          image: ghcr.io/drogue-iot/http-endpoint:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: debug
            - name: BIND_ADDR
              value: "0.0.0.0:8443"
            - name: AUTH_SERVICE_URL
              value: http://authentication-service:8080
            - name: CERT_BUNDLE_FILE
              value: /etc/endpoint/tls.crt
            - name: KEY_FILE
              value: /etc/endpoint/tls.key
            - name: INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: instance
          ports:
            - containerPort: 8443
              name: endpoint
              protocol: TCP
            - containerPort: 8081
              name: command
              protocol: TCP
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: 8443
              path: /health
          volumeMounts:
            - mountPath: /etc/endpoint
              name: endpoint-tls
      volumes:
        - name: endpoint-tls
          secret:
            secretName: http-endpoint-tls
