apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: http-endpoint
  labels:
    image-source: build
    app.kubernetes.io/part-of: endpoints
spec:
  template:
    metadata:
      labels:
        image-source: build
        bindings.knative.dev/include: "true"
    spec:
      containers:
        - image: ghcr.io/drogue-iot/http-endpoint:latest
          env:
            - name: RUST_LOG
              value: info
            - name: ENABLE_AUTH
              value: "true"
            - name: AUTH_SERVICE_URL
              value: http://authentication-service:8080
