apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: bind-http-endpoint
  labels:
    app.kubernetes.io/part-of: endpoints
spec:

  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: http-endpoint

  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: KafkaSink
      name: iot-events
