apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - configuration
  - knative
  - sso
  - source/http
  - source/mqtt
  - source/command
  - service/influxdb
  - service/grafana
  - service/console
  - service/registry
