
global:
  # cluster defines the cluster type
  cluster: kubernetes
  domain: .my-cluster.dns
  instance: drogue


endpoints:

  http:
    insecure: false
    ingress:
      port: 443

  mqtt:
    ingress:
      port: 8883


integrations:

  mqtt:
    ingress:
      port: 8883


defaults:
  images:
    repository: ghcr.io/drogue-iot
    # pullPolicy Sets the pull policy explicitly. Defaults to Always when using the 'latest'
    #   tag and to IfNotPresent otherwise.
    # pullPolicy: IfNotPresent
    # tag The container tag to apply. Defaults to the chart's application version
    # tag: latest


keycloak:
  adminPassword: admin123456
  identityProviders: []
  postgres:
    # mode is the way postgres gets configured. This can be:
    #  - drogue: Re-use the Drogue Cloud postgres instance
    #  - operator: Let the keycloak operate manage one
    #  - external: Use an external instance
    mode: drogue # reuse drogue instance
    # username: foo
    # password: bar
    # you can provider either:
    #   url: jdbc:postgresql://foo/bar
    # or:
    #   host: postgres
    #   port: 5678
    #   databaseName: keycloak


postgres:
  databaseName: registry
  username: admin
  password: admin123456
  podSecurityContext:
    enabled: false


kafka:
  podSecurityContext:
    enabled: false
