{{ if eq .Values.cluster "openshift"}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqtt-integration
spec:
  to:
    kind: Service
    name: mqtt-integration
  port:
    targetPort: service
  tls:
    termination: passthrough
{{- end }}