kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - # we omit the host here, it needs to be set later on, based on the application domain
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: endpoint
          - path: /.well-known/
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: endpoint
          - path: /api/console/
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: endpoint
          - path: /api/keys/
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: endpoint
          - path: /api/admin/v1alpha1/user
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: endpoint
          - path: /api/admin/v1alpha1/apps
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  name: api
          - path: /api/registry/
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  name: api
          - path: /api/command/
            pathType: Prefix
            backend:
              service:
                name: command-endpoint
                port:
                  name: endpoint
