apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: ttn-operator
  labels:
    app.kubernetes.io/name: ttn-operator
    app.kubernetes.io/part-of: device-registry
spec:
  consumerGroup: ttn-operator
  bootstrapServers:
    - drogue-iot-kafka-bootstrap.{{ .Release.Namespace }}.svc.cluster.local.:9092
  topics:
    - registry
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: ttn-operator
