apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ttn-operator
rules:
  - apiGroups: [ "route.openshift.io" ]
    resources: [ "routes" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "serving.knative.dev" ]
    resources: [ "services" ]
    verbs: [ "get", "watch", "list" ]
