kind: Deployment
apiVersion: apps/v1
metadata:
  name: console-frontend
  labels:
    app: console-frontend
    app.kubernetes.io/part-of: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-frontend
  template:
    metadata:
      labels:
        app: console-frontend
    spec:
      containers:
        - name: endpoint
          image: {{ include "drogue-cloud-core.image-repo" . }}console-frontend:{{ include "drogue-cloud-core.image-tag" . }}
          imagePullPolicy: {{ .Values.defaults.images.pullPolicy }}
          env:
            - name: API_URL
              value: {{ include "drogue-cloud-common.api.url" . }}
          ports:
            - containerPort: 8080
              name: endpoint
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
          volumeMounts:
            - mountPath: /run
              name: run
            - mountPath: /endpoints
              name: endpoints
            - mountPath: /etc/config/login
              name: login-config
              readOnly: true
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /
      volumes:
        - name: run
          emptyDir: {}
        - name: endpoints
          emptyDir: {}
        - name: login-config
          configMap:
            optional: true
            name: login-config
