kind: Deployment
apiVersion: apps/v1
metadata:
  name: console-backend
  labels:
    app: console-backend
    app.kubernetes.io/part-of: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-backend
  template:
    metadata:
      labels:
        app: console-backend
    spec:
      serviceAccountName: console-backend
      containers:
        - name: endpoint
          image: ghcr.io/drogue-iot/console-backend:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: BIND_ADDR
              value: "0.0.0.0:8080"
            - name: ENABLE_AUTH
              value: "true"
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-drogue
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-drogue
                  key: CLIENT_SECRET
          ports:
            - containerPort: 8080
              name: endpoint
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
