apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account-backend.yaml
  - role-backend.yaml
  - role-binding-backend.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-frontend.yaml
