apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-endpoint
  labels:
    app.kubernetes.io/name: command-endpoint
    app.kubernetes.io/part-of: endpoints
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: command-endpoint
      app.kubernetes.io/part-of: endpoints
  template:
    metadata:
      labels:
        app.kubernetes.io/name: command-endpoint
        app.kubernetes.io/part-of: endpoints
    spec:
      initContainers:
        - name: wait-for-client-secret
          image: registry.access.redhat.com/ubi8-minimal
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - |
              echo "Waiting for client secret to be populated (/etc/client-secret/CLIENT_SECRET)..."
              while test -z "$(cat /etc/client-secret/CLIENT_SECRET)"; do
                sleep 1
              done
          volumeMounts:
            - mountPath: /etc/client-secret
              name: client-secret
              readOnly: true
      containers:
        - name: endpoint
          image: ghcr.io/drogue-iot/command-endpoint:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: debug
            - name: BIND_ADDR
              value: "0.0.0.0:8080"
            - name: INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: instance
            # this is a workaround as the name of the variable conflicts with an automatically generated
            # variable from Kubernetes, which doesn't parse as an int
            - name: MQTT_ENDPOINT_PORT
              value: "0"
            # this is a workaround as the name of the variable conflicts with an automatically generated
            # variable from Kubernetes, which doesn't parse as an int
            - name: MQTT_INTEGRATION_PORT
              value: "0"
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_SECRET
          ports:
            - containerPort: 8080
              name: endpoint
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
      volumes:
        - name: client-secret
          secret:
            secretName: keycloak-client-secret-drogue