apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: commands-mqtt
  labels:
    app.kubernetes.io/part-of: endpoints
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: iot-commands
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: mqtt-command
    uri: /command-service
