
# Ports might seem a bit off, but they must be in the range of 30000-32767

drogueCloudCore:

  endpoints:
    coap:
      ingress:
        port: 30003
    mqtt:
      ingress:
        port: 30001
    mqttWs:
      ingress:
        port: 30005
    mqttWsBrowser:
      ingress:
        port: 30007
    http:
      ingress:
        port: 30443

  integrations:
    mqtt:
      ingress:
        port: 30002
    mqttWs:
      ingress:
        port: 30006
    mqttWsBrowser:
      ingress:
        port: 30008
    websocket:
      insecure: true
      ingress:
        port: 30004

  defaults:
    ingress:
      className: nginx

  console:
    localCertificates: true

  oauth2:
    tls:
      insecure: true

  services:
    sso:
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/server-snippet: |2-
                              location ~* "^/realms/master/metrics" {
                                  return 301 /realms/master;
                              }
