apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: bind-http-insecure-endpoint
  labels:
    app.kubernetes.io/part-of: endpoints
spec:

  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: http-insecure-endpoint

  sink:
    ref:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: KafkaChannel
      name: iot-channel
